
/*
 *  Copyright (c) 2022 Qonic
 *
 *  This file is auto-generated.
 *
 *  Do not modify manually!
 */


namespace Ifc
{
    public enum IfcDerivedUnitEnum : byte
    {
        Null = 0,
        ANGULARVELOCITYUNIT = 1,
        AREADENSITYUNIT = 2,
        COMPOUNDPLANEANGLEUNIT = 3,
        DYNAMICVISCOSITYUNIT = 4,
        HEATFLUXDENSITYUNIT = 5,
        INTEGERCOUNTRATEUNIT = 6,
        ISOTHERMALMOISTURECAPACITYUNIT = 7,
        KINEMATICVISCOSITYUNIT = 8,
        LINEARVELOCITYUNIT = 9,
        MASSDENSITYUNIT = 10,
        MASSFLOWRATEUNIT = 11,
        MOISTUREDIFFUSIVITYUNIT = 12,
        MOLECULARWEIGHTUNIT = 13,
        SPECIFICHEATCAPACITYUNIT = 14,
        THERMALADMITTANCEUNIT = 15,
        THERMALCONDUCTANCEUNIT = 16,
        THERMALRESISTANCEUNIT = 17,
        THERMALTRANSMITTANCEUNIT = 18,
        VAPORPERMEABILITYUNIT = 19,
        VOLUMETRICFLOWRATEUNIT = 20,
        ROTATIONALFREQUENCYUNIT = 21,
        TORQUEUNIT = 22,
        MOMENTOFINERTIAUNIT = 23,
        LINEARMOMENTUNIT = 24,
        LINEARFORCEUNIT = 25,
        PLANARFORCEUNIT = 26,
        MODULUSOFELASTICITYUNIT = 27,
        SHEARMODULUSUNIT = 28,
        LINEARSTIFFNESSUNIT = 29,
        ROTATIONALSTIFFNESSUNIT = 30,
        MODULUSOFSUBGRADEREACTIONUNIT = 31,
        ACCELERATIONUNIT = 32,
        CURVATUREUNIT = 33,
        HEATINGVALUEUNIT = 34,
        IONCONCENTRATIONUNIT = 35,
        LUMINOUSINTENSITYDISTRIBUTIONUNIT = 36,
        MASSPERLENGTHUNIT = 37,
        MODULUSOFLINEARSUBGRADEREACTIONUNIT = 38,
        MODULUSOFROTATIONALSUBGRADEREACTIONUNIT = 39,
        PHUNIT = 40,
        ROTATIONALMASSUNIT = 41,
        SECTIONAREAINTEGRALUNIT = 42,
        SECTIONMODULUSUNIT = 43,
        SOUNDPOWERLEVELUNIT = 44,
        SOUNDPOWERUNIT = 45,
        SOUNDPRESSURELEVELUNIT = 46,
        SOUNDPRESSUREUNIT = 47,
        TEMPERATUREGRADIENTUNIT = 48,
        TEMPERATURERATEOFCHANGEUNIT = 49,
        THERMALEXPANSIONCOEFFICIENTUNIT = 50,
        WARPINGCONSTANTUNIT = 51,
        WARPINGMOMENTUNIT = 52,
        USERDEFINED = 53,
    }
}