
/*
 *  Copyright (c) 2022 Qonic
 *
 *  This file is auto-generated.
 *
 *  Do not modify manually!
 */


namespace Ifc
{
    public enum IfcEvaporativeCoolerTypeEnum : byte
    {
        Null = 0,
        DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER = 1,
        DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER = 2,
        DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER = 3,
        DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER = 4,
        DIRECTEVAPORATIVEAIRWASHER = 5,
        INDIRECTEVAPORATIVEPACKAGEAIRCOOLER = 6,
        INDIRECTEVAPORATIVEWETCOIL = 7,
        INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER = 8,
        INDIRECTDIRECTCOMBINATION = 9,
        USERDEFINED = 10,
        NOTDEFINED = 11,
    }
}